EMC_pr/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/', include('patient_info.urls')),
    path('accounts/', include('accounts.urls')),
]

patient_info/urls.py
from django.urls import path
from .views import AllPAtientsListView, PatientListView, PatientActiveListView, SearchPatient, hide_patient, PatientDetailView, RecordDetailView, PatientCreateView, PatientUpdateView, RecordCreateView, RecordUpdateView

urlpatterns = [
    path("", PatientListView.as_view(), name="PatientList"),
    path("patients-active/", PatientActiveListView.as_view(), name="PatientsActiveList"),
    path("delete-patient_<int:patient_id>", hide_patient, name="DeletePatient"),
    path("<int:pk>/", PatientDetailView.as_view(), name="PatientDetail"),
    path("<int:patient_id>/record/<int:pk>", RecordDetailView.as_view(), name="RecordDetail"),
    path("create_patient", PatientCreateView.as_view(), name="PatientCreate"),
    path("update_patient/<int:pk>", PatientUpdateView.as_view(), name="PatientUpdate"),
    path("create_record/<int:patient_id>", RecordCreateView.as_view(), name="RecordCreate"),
    path("update_record/patient/<int:patient_id>/record/<int:pk>", RecordUpdateView.as_view(), name="RecordUpdate"),
    path('search/', SearchPatient, name="Search"),
    path("all", AllPAtientsListView.as_view(), name="AllPatients"),
]

patient_info/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Patient(models.Model):
    fullname = models.CharField(max_length=100, unique=True, verbose_name='Ф.И.О.')
    dob = models.DateField(verbose_name='Дата рождения')
    room = models.SmallIntegerField(blank=True, null=True, verbose_name='Номер палаты')
    is_active = models.BooleanField(default=False, verbose_name='Госпитализирован в данный момент?')
    hided = models.BooleanField(default=False)
    
    srisk = models.BooleanField(default=False, verbose_name='Суицидальный риск')
    self_harm = models.BooleanField(default=False, verbose_name='Самоповреждения')
    drisk = models.BooleanField(default=False, verbose_name='Риск падения')

    def __str__(self):
        return self.fullname

    def age(self):
        import datetime
        return int((datetime.date.today() - self.dob).days / 365.25  )
    

class Info(models.Model):

    S_RISK_CHOICES = [
        (0, "Нет"),
        (1, "Низкий"),
        (2, "Высокий"),
    ]

    current_date = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    suicidal_risk = models.SmallIntegerField(choices=S_RISK_CHOICES, blank=False, null=False)
    bathroom_time = models.PositiveSmallIntegerField(blank=True, null=True)
    record = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return ('{date} - {patient}').format(date=self.current_date, patient=self.patient)

    class Meta:
        ordering = ['-current_date']

patient_info/forms.py
from django import forms
from .models import Patient, Info

class AddPatientForm(forms.Form):
    class Meta:
        model = Patient
        fields = ("fullname", "dob", "room",)
        labels = {"fullname": "ФИО", "dob": "Дата рождения", "room": "Палата"}

class AddRecordForm(forms.ModelForm):
    # bathroom = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control-range', 'type': 'range', "min": "1", "max": "60", "step": "0,17"}))
    class Meta:
        model = Info
        fields = ("suicidal_risk", "bathroom_time", "record", "patient", "bathroom_time",)
        labels = {"suicidal_risk": "Суицидальный риск", "record": "Комментарии", "bathroom_time": "Время в туалете"}
        widgets = {'patient': forms.HiddenInput(),
                    "suicidal_risk": forms.RadioSelect(attrs={'class':"suicidal"}),
                    "record": forms.Textarea(attrs={'class':"text_cls"}),
                    }

patient_info/views.py
from django.shortcuts import render, render_to_response
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView
from .models import Patient, Info
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from .forms import AddRecordForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from accounts.models import Profile
from django.contrib.auth.models import User

class PatientListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    queryset = Patient.objects.filter(hided=False).order_by("-is_active", "fullname",)
    # paginate_by = 20
    context_object_name = "patients"
    template_name="patient_info/patients.html"


    def test_func(self):
        # return self.request.user.email.endswith("@emcmos.ru")
        # profile = Profile.objects.get(user = self.request.user)
        # return profile.occupation == "D"
        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user = self.request.user)
        context["profile"] = profile.occupation
        return context


@login_required
def hide_patient(request, patient_id):
    patient = Patient.objects.get(id=patient_id)
    patient.hided = True
    patient.save()
    return redirect(reverse_lazy("AllPatients"))

class PatientActiveListView(LoginRequiredMixin, ListView):
    queryset = Patient.objects.filter(is_active=True).order_by("room")
    context_object_name = "patients"
    template_name="patient_info/patients_active.html"

class PatientDetailView(LoginRequiredMixin, DetailView):

    model = Patient
    context_object_name = "patient"
    template_name = "patient_info/patient_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["records"] = Info.objects.filter(patient=self.object)
        return context

class RecordDetailView(LoginRequiredMixin, DetailView):
    model = Info
    context_object_name = "record"
    template_name = "patient_info/record_detail.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["patient"] = Patient.objects.get(id=self.kwargs["patient_id"])
        return context

class PatientCreateView(LoginRequiredMixin, CreateView):
    model=Patient
    context_object_name = "patient"
    fields = ["fullname", "dob", "room", "is_active",]
    template_name = "patient_info/create_patient.html"
    success_url = reverse_lazy('PatientList')


class PatientUpdateView(LoginRequiredMixin, UpdateView):
    model=Patient
    context_object_name = "patient"
    fields = ["fullname", "dob", "room", "is_active", "srisk", "drisk", "self_harm"]
    template_name = "patient_info/update_patient.html"

    def get_success_url(self, **kwargs):
        return reverse_lazy("PatientDetail", kwargs={'pk': self.kwargs["pk"]})

class RecordCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        form = AddRecordForm(request.POST)
        form.initial['patient'] = Patient.objects.get(id=self.kwargs["patient_id"])
        # form.initial['owner'] = User.objects.get(username = request.user)
        if form.is_valid():
            record = form.save(commit=False)
            record.owner = request.user
            # bathroom_time = form["bathroom"]
            form.save()
            return redirect(reverse_lazy("PatientDetail", kwargs={"pk": self.kwargs["patient_id"]}))
        return render(request, "patient_info/create_record.html", {"form": form})

    def get(self, request, *args, **kwargs):
        form = AddRecordForm()
        form.initial['patient'] = Patient.objects.get(id=self.kwargs["patient_id"])
        patient_id = self.kwargs["patient_id"]
        patient_name = Patient.objects.get(id=self.kwargs["patient_id"]).fullname
        patient = Patient.objects.get(id=self.kwargs["patient_id"])
        return render(request, "patient_info/create_record.html", {"form": form, "patient_id": patient_id, "patient_name": patient_name, "patient": patient})

    
class RecordUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model=Info
    context_object_name = "record"
    fields = ["suicidal_risk", "bathroom_time", "record",]
    template_name = "patient_info/update_record.html"
    success_message = "Запись изменена"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["patient"] = Patient.objects.get(id=self.kwargs["patient_id"])
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("PatientDetail", kwargs={'pk': self.kwargs["patient_id"]})
    
    # Only owner allow to update
    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update stories """
        obj = self.get_object()
        if obj.owner != self.request.user:
            messages.add_message(request, messages.INFO, extra_tags="alert-danger alert-dismissible",message='Вы можете менять только свои записи')
            return redirect(reverse_lazy("PatientDetail", kwargs={'pk': self.kwargs["patient_id"]}))
        return super(RecordUpdateView, self).dispatch(request, *args, **kwargs)

@login_required
def SearchPatient(request):
    
    if request.method == "POST":
        search_text = request.POST['search_text']
    else:
        search_text = ""
    
    patients = Patient.objects.filter(fullname__contains=search_text)[:5]
    return render_to_response('patient_info/ajax_search.html', {"patients": patients})

class AllPAtientsListView(LoginRequiredMixin, ListView):
    queryset = Patient.objects.filter(hided=False).order_by("-is_active", "fullname",)
    model = Patient
    paginate_by = 20
    context_object_name = "patients"
    template_name = 'patient_info/patients_db.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user = self.request.user)
        context["profile"] = profile.occupation
        return context

patient_info/templates/patient_info/ajax_search.html
{% if patients.count > 0 %}
    <div class="search-container">
        {%for patient in patients%}
        <li><a href="/patients/{{patient.id}}" class="search-results">{{patient.fullname}}</a></li>
        {% endfor %}   
    </div>
    

{% else %}

    <li>None to show!</li>

{% endif %}

patient_info/templates/patient_info/create_patient.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Запись {{record.current_date}}{% endblock %}

{% block main_content %}
    <h1>Создать пациента:</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

patient_info/templates/patient_info/create_record.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Запись {{record.current_date}}{% endblock %}

{% block main_content %}


    <div class="col-6 col-md-12">

            <div class="mt-3">
                    {% if patient.srisk %}
                            <div class="m-2 p-2 col-6  col-md-8 border border-danger rounded shadow-sm alarm-card mx-auto">                        
                                        <h5 class="title"><img src="{% static 'img/gallows1.svg' %}" alt="My image" width='40px'> Пациент с суицидальным риском</h5>
                                        <ul>
                                            <li>Рядом не должно быть острых предметов</li><hr>
                                            <li>Следить за временем, проведенным в туалете</li><hr>
                                            <li>Не оставлять одного</li>
                                        </ul>
                                </div>
                            
                    {% endif %}
                    {% if patient.drisk %}
                        <div class="m-2 p-2 col-6  col-md-8 border border-warning rounded shadow-sm alarm-card mx-auto">                        
                                    <h5 class="title"><img src="{% static 'img/accident.png' %}" alt="My image" width='40px'> Пациент с риском падения</h5>
                                    <ul>
                                        <li>При необходимости помогать подниматься с кровати</li><hr>
                                        <li>Сопровождать во время движения</li><hr>
                                    </ul>
                            </div>
                            
                    {% endif %}
                    {% if patient.self_harm %}
                        <div class="m-2 p-2 col-6 col-md-8 border border-dark rounded shadow-sm alarm-card mx-auto">                        
                                    <h5 class="title"><img src="{% static 'img/self-harm1.svg' %}" alt="My image" width='40px'> Риск самоповреждения</h5>
                                    <ul>
                                        <li>Рядом не должно быть острых предметов</li><hr>
                                        <li>Следить за временем, проведенным в туалете</li><hr>
                                        <li>После еды убирать вилки и ножи</li>
                                    </ul>
                            </div>
                            
                    {% endif %}
                </div>

            <h1>Создать запись для пациента {{patient_name}}:</h1>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}        
            <input type="submit" value="Save" class="btn btn-primary">
        </form>
        <a href={% url "PatientDetail" patient_id %} class="btn btn-primary">Назад</a>
    </div>  
    

{% endblock %}

patient_info/templates/patient_info/patient_detail.html
{%extends 'base.html' %}
{% load static %}
{% block title %}{{patient.fullname}}{% endblock %}

{% block main_content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    {% if message.tags != 'success' %}
        <div class="alert {{message.tags}}" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
        </div>
    {% else %}
        <div class="alert alert-success" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
        </div>
    {% endif %}
    
    {% endfor %}
</ul>
{% endif %}


    <h2>Пациент {{patient.fullname}}  {{patient.age}} лет ({{patient.dob|date:"d-m-Y"}}) --  палата №{{patient.room}}</h2>
    <ul class="list-group" style="width: 50%;"> 
        {% for record in records %}

        <a href= {% url "RecordDetail" patient.id record.id %} class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">Запись индивидуального поста</h5>
                  <small>{{record.current_date|timesince}}</small>
                </div>
                <small>{{record.current_date|date:"d-m-Y H:i"}}</small>
                {% if record.suicidal_risk == 2 %}
                <span class="badge badge-pill badge-danger ml-3">Высокий S-риск</span>
                {% endif %}
              </a>


            <!-- <li class="list-group-item"><a href= {% url "RecordDetail" patient.id record.id %}>Запись от {{record.current_date|date:"d-m-Y H:i"}}</a></li> -->
        {% endfor %}
    </ul>

    <a href={% url "PatientUpdate" patient.id %} class="btn btn-primary mt-5">Изменить данные пациента</a>
    <a href={% url "RecordCreate" patient.id %} class="btn btn-primary mt-5">Создать запись</a>
{% endblock %}

patient_info/templates/patient_info/patients.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Patients{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="patients-container col-12 col-md-8">
                <h1 class="patients-header">Список пациентов в стационаре</h1>
                <div class="row mt-5">
                    {% for patient in patients %}
                    {% if patient.is_active %}
                    <div class="col">
                        <div {% if patient.age < 18 %}class="shadow-sm card border-danger mb-3 patient-card"{% else %}class="shadow-sm card bg-light mb-3 patient-card"{% endif %} style="width: 15rem;" >
                            <div class="card-header">{{patient.fullname}} 
                                                    {% if patient.age == 1 %}{{patient.age}} год 
                                                    {% elif patient.age > 1 and patient.age < 4  %} {{patient.age}} года
                                                    {% elif patient.age == 22 or patient.age == 33 or patient.age == 44 %} {{patient.age}} года 
                                                    {% else %} {{patient.age}} лет
                                                    {% endif %}

                                                    {% if patient.srisk %}
                                                    <span class="badge badge-danger"><abbr title="Суицидальный риск" class="initialism">S</abbr></span>
                                                    {% endif %} 

                                                    {% if patient.drisk %}
                                                    <span class="badge badge-warning"><abbr title="Риск падения" class="initialism">П</abbr></span>
                                                    {% endif %}

                                                    {% if patient.self_harm %}
                                                    <span class="badge badge-dark"><abbr title="Риск самоповреждния" class="initialism">Sh</abbr></span>
                                                    {% endif %}
                                                </div>
                            
                            <div class="card-body">
                                <h6 class="card-subtitle mb-2 text-muted">{{patient.room}} палата</h6>
                                <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                                <a href={% url "PatientDetail" patient.id %} class="card-link">Записи</a>
                            </div>
                        </div>
                    </div>        
                    {% endif %}                        
                    {% endfor %}
                </div>
        </div>
          
        {% if profile == 'D' %}
        <div class="search_field col-12 col-md-4 mt-3  border-left">
            <form>{% csrf_token %}
                <div class="form-group">
                    <label for="search">Поиск пациента</label>
                    <input type="search" id="search" name="search" class="form-control form-control-sm search-input" placeholder="Начните вводить..."/>
                    <ul id="search-results"></ul>
                    <small id="emailHelp" class="form-text text-muted">Never share it</small>
                </div>
            </form>
        </div>
        {% endif %}
    </div>
    
    

    
  
    

    </ul>



{% endblock %}

patient_info/templates/patient_info/patients_active.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Patients{% endblock %}

{% block main_content %}
    <h1 class="patients-header">Список пациентов в стационаре</h1>
    <div class="row mt-5">
        {% for patient in patients %}
        <div class="col-3">
            <div class="shadow-sm card bg-light mb-3 patient-card" style="width: 15rem;" >
                <div class="card-header">{{patient.fullname}}</div>
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">{{patient.room}} палата</h6>
                    <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                    <a href={% url "PatientDetail" patient.id %} class="card-link">Записи</a>
                </div>
            </div>
        </div>            
        {% endfor %}
    </div>
    <!-- <ul>
        {% for patient in patients %}
            <!-- <li><a href={% url "PatientDetail" patient.id %}>{{patient.room}} палата {{patient.fullname}}</a></li> -->
    <!-- </ul>   -->
    <!-- {% endfor %}  -->

{% endblock %}

patient_info/templates/patient_info/patients_db.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Patients{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="patients-container col">
            <h1>Список пациентов:</h1>
            <ul>
                {% for patient in patients %}
                        {% if patient.is_active %}
                            <li class="patient-elem active-patient-elem"><span class="badge badge badge-secondary">{{patient.room}} п.</span> <a href={% url "PatientDetail" patient.id %}>{{patient.fullname}}</a> <a class="delete text-monospace" href={% url "DeletePatient" patient.id %}>X</a>
                        {% else %}
                            <li class="patient-elem inactive-patient-elem"><a href={% url "PatientDetail" patient.id %}>{{patient.fullname}}</a> <a class="delete text-monospace" href={% url "DeletePatient" patient.id %}>X</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>

            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination mt-5 mb-5">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Назад</a>
                            {% endif %}
                            <span class="page-current">
                                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Далее</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}
            <a href={% url "PatientCreate" %} class="btn btn-primary">Создать пациента</a>
        </div>
          
        <div class="search_field mt-5 col-12 col-md-4 ">
            <form>{% csrf_token %}
                <div class="form-group">
                    <label for="search">Поиск пациента</label>
                    <input type="text" id="search" name="search" class="form-control form-control-sm search-input" placeholder="Начните вводить..."/>
                    <ul id="search-results"></ul>
                    <small id="emailHelp" class="form-text text-muted">Never share it</small>
                </div>

            </form>
        </div>
    </div>
    
    

    
  
    

    </ul>



{% endblock %}

patient_info/templates/patient_info/record_detail.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Запись {{record.current_date}}{% endblock %}

{% block main_content %}
    <h1>Запись ИП от {{record.current_date|date:"d-m-Y H:i"}}:</h1>
    <p>ФИО пациента: {{patient.fullname}}</p>
    <p>Комментарии: {{record.record}}</p>
    <p>Суицидальный риск: {{record.get_suicidal_risk_display}}</p>

    <a href={% url "RecordUpdate" patient.id record.pk %} class="btn btn-primary">Изменить запись</a>
    <a href={% url "PatientDetail" patient.id %} class="btn btn-primary">Назад</a>
{% endblock %}

patient_info/templates/patient_info/update_patient.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Запись {{patient.fullname}}{% endblock %}

{% block main_content %}
    <h1>Изменить данные пациента: {{patient.fullname}}</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary">
    </form>

{% endblock %}

patient_info/templates/patient_info/update_record.html
{%extends 'base.html' %}
{% load static %}
{% block title %}Запись {{record.current_date}}{% endblock %}

{% block main_content %}
    <h1>Изменить данные записи: {{patient.fullname}}</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}